spring.application.name=desafio-itau
spring.banner.location=banner.txt

logging.level.root=INFO
logging.file.name=logs/desafio-itau.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%t] %-40.40logger{39} : %m%n